### ISSUE TITLE
Road map to Stable v1.0 release

### ISSUE THREAD

**Issue by mattma** [mattma/coreos-distro#9]
- [ ] Current, if you run the [update-demo example](https://github.com/mattma/coreos-distro/tree/master/examples/update-demo) in the cluster, it will work in all cases. Except that it cannot access the pod data by using API server endpoint via [`proxy/namespaces/default/pods/" + server.podId + "/data.json`](https://github.com/mattma/coreos-distro/blob/master/examples/update-demo/local/script.js#L4). Compare with the original [update-demo](https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/update-demo/local/script.js#L20) in Kubernetes repo.
- [ ] Using images/containers instead of curl/wget binary. See [Issue 5](https://github.com/mattma/coreos-distro/issues/5)
- [ ] configuration instead of hard code values. See [Issue 7](https://github.com/mattma/coreos-distro/issues/7)
- [ ] User need an authentication to access the API server. via `secret`, `ssh key`, etc.
- [ ] Test in the production machines. Form a cluster, to see how it perform via `kubectl` command from local machine.
- [ ] Write an documentation for how to deploy to a production environment. Ex: "digitial ocean", "AWS", etc
- [ ] Three master nodes for high availabilties. Based on the [design goal](https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/high-availability.md)
- [ ] Provide an easy update path when a newer version of the kubernetes release via `Environment Variable`
- [ ] Current implementation of [`dns controller`](https://github.com/mattma/coreos-distro/blob/master/setup/dns/dns-controller.yaml) is borrowed from [here](https://github.com/pires/kubernetes-vagrant-coreos-cluster/blob/master/dns/dns-controller.yaml.tmpl). Need someone who is knowledgable on this topic to review it.
- [ ] HTTP proxy service. Do we need this [proxy service](https://github.com/pires/kubernetes-vagrant-coreos-cluster/blob/master/master.yaml#L42)?
- [ ] Do we need to have [rpcbind.service](https://github.com/mattma/coreos-distro/blob/master/setup/cloud-init/master-data#L25) and [rpc-statd.service](https://github.com/mattma/coreos-distro/blob/master/setup/cloud-init/master-data#L29)?
- [ ] Someone from In-depth _kubernetes_ background could review all the [units files](https://github.com/mattma/coreos-distro/tree/master/units).
- [ ] Support for service-account and tokens. [See here](https://github.com/pires/kubernetes-vagrant-coreos-cluster/blob/master/kube-serviceaccount.key)

**Comment by mattma** [comment]
@yichengq I have built up a list to sum up **ROAD TO 1.0**. Feel free to add more. We will track them in the central place here.
